substitutions:
  device_name: "display35"
  friendly_name: Display35

packages:
  device_base: !include lib/3248s035_base.yaml
  lib: !include lib/lib.yaml

esphome:
  name: $device_name
  friendly_name: $friendly_name

api:
  encryption: 
    key: "AJ9ioMY1QzbUlAKim6G9IAYEVDv5a6iJCToD7lppTLU="

globals:
  - id: rows
    type: int
    initial_value: "2"
  - id: cols
    type: int
    initial_value: "3"

tile_ui:
  tiles_file: monitor_tiles.yaml